# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b0254080c0887bb2cfce9de1b07fc9f57f447be932b62307969cc80e284243046d044221a045ce8a6a9de9fb9292d14f31ac7e5d796b197445b5839ef087eda

test:
  secret_key_base: 0062ec00f5087bb6eacf8656325ebf9ff6e13905b2568cacaae0422a136e65a372e595f64b375bc5bf8ed52499abc661276d4ac71ce7621306d88e6a10c2f22b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
